<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TipoDocumentoSeeder extends Seeder
{
    public function run(): void
    {
$now = Carbon::now();


$documentos = [

    [
        'nombre'            => 'Certificado de Nacido Vivo',
        'cod_rips'          => 'CN',
        'cod_dian'          => '00',
        'es_nacional'       => true,
        'es_paciente'       => true,
        'es_pagador'        => false,
        'requiere_acudiente'=> true,
        'edad_minima'       => 0,
        'edad_maxima'       => 3,
        'regex_validacion'  => '^[A-Z0-9]{9,20}$',
        'nivel'             => 3,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Registro Civil',
        'cod_rips'          => 'RC',
        'cod_dian'          => '11',
        'es_nacional'       => true,
        'es_paciente'       => true,
        'es_pagador'        => false,
        'requiere_acudiente'=> true,
        'edad_minima'       => 0,
        'edad_maxima'       => 7,
        'regex_validacion'  => '^[A-Z0-9]{4,11}$',
        'nivel'             => 5,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Tarjeta de Identidad',
        'cod_rips'          => 'TI',
        'cod_dian'          => '12',
        'es_nacional'       => true,
        'es_paciente'       => true,
        'es_pagador'        => false,
        'requiere_acudiente'=> true,
        'edad_minima'       => 7,
        'edad_maxima'       => 18,
        'regex_validacion'  => '^[0-9]{10,11}$',
        'nivel'             => 8,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Cédula de Ciudadanía',
        'cod_rips'          => 'CC',
        'cod_dian'          => '13',
        'es_nacional'       => true,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 18,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[0-9]{4,10}$',
        'nivel'             => 11,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Sin identificación',
        'cod_rips'          => 'SI',
        'cod_dian'          => '99',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => false,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,20}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Tarjeta de Extranjería',
        'cod_rips'          => 'DE',
        'cod_dian'          => '21',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 17,
        'regex_validacion'  => '^[A-Z0-9]{6,20}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Cédula de Extranjería',
        'cod_rips'          => 'CE',
        'cod_dian'          => '22',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 18,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,6}$',
        'nivel'             => 1,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Pasaporte',
        'cod_rips'          => 'PA',
        'cod_dian'          => '41',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,16}$',
        'nivel'             => 4,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Documento de identificación extranjero (otro)',
        'cod_rips'          => 'DE',
        'cod_dian'          => '42',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,25}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Salvoconducto',
        'cod_rips'          => 'SC',
        'cod_dian'          => '42',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,16}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Permiso Especial de Permanencia (PEP)',
        'cod_rips'          => 'PE',
        'cod_dian'          => '43',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,15}$',
        'nivel'             => 4,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'PEP-RAMV',
        'cod_rips'          => 'PT',
        'cod_dian'          => '44',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,25}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Permiso por Protección Temporal (PPT)',
        'cod_rips'          => 'PT',
        'cod_dian'          => '47',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,25}$',
        'nivel'             => 4,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'NIT',
        'cod_rips'          => 'NI',
        'cod_dian'          => '91',
        'es_nacional'       => true,
        'es_paciente'       => false,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 0,
        'regex_validacion'  => '^[0-9]{3,13}$',
        'nivel'             => 1,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Carné Diplomatico',
        'cod_rips'          => 'CD',
        'cod_dian'          => '46',
        'es_nacional'       => false,
        'es_paciente'       => true,
        'es_pagador'        => true,
        'requiere_acudiente'=> false,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[A-Z0-9]{3,16}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'NUI (Número Único de Identificación - SISBEN)',
        'cod_rips'          => 'NU',
        'cod_dian'          => '92',
        'es_nacional'       => true,
        'es_paciente'       => true,
        'es_pagador'        => false,
        'requiere_acudiente'=> true,
        'edad_minima'       => 0,
        'edad_maxima'       => 130,
        'regex_validacion'  => '^[0-9]{10}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
    [
        'nombre'            => 'Menor sin identificación',
        'cod_rips'          => 'MS',
        'cod_dian'          => '98',
        'es_nacional'       => true,
        'es_paciente'       => true,
        'es_pagador'        => false,
        'requiere_acudiente'=> true,
        'edad_minima'       => 0,
        'edad_maxima'       => 17,
        'regex_validacion'  => '^\d{2}\d{3}[SIDAP]\d{4,}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ],
      [
        'nombre'            => 'Adulto sin identificación',
        'cod_rips'          => 'AS',
        'cod_dian'          => '98',
        'es_nacional'       => true,
        'es_paciente'       => true,
        'es_pagador'        => false,
        'requiere_acudiente'=> true,
        'edad_minima'       => 0,
        'edad_maxima'       => 17,
        'regex_validacion'  => '^\d{2}\d{3}[SIDAP]\d{4,}$',
        'nivel'             => 0,
        'created_at'        => $now,
        'updated_at'        => $now,
    ]

];

        DB::table('tipo_documentos')->insert(
            $documentos
        );
}
}
