# docker login -u puller -p KkzSsl1yqmCEvjiTvzmrSvcXqWEcAbHclVehxIJqdU+ACRC0WuUB crmspsgovcoprd.azurecr.io
# docker-compose -f apilocal-dockercompose.Production.yml pull
# docker-compose -f apilocal-dockercompose.Production.yml up -d


networks:

    fevrips-net:
        driver: bridge


services:

    fevrips-db:
        container_name: fevrips-db
        image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
        deploy:
            resources:
                limits:
                    cpus: '4.00'
                    memory: 9G
                reservations:
                    cpus: '3.00'
                    memory: 6G
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=FEVRIPS1*
            - MSSQL_MEMORY_LIMIT_MB=9000
            - MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS
            - MSSQL_PID=Enterprise
        networks:
          - fevrips-net

    fevrips-api:
        container_name: fevrips-api
        image: crmspsgovcoprd.azurecr.io/production-fevrips-apilocal
        deploy:
            resources:
                limits:
                    cpus: '4.00'
                    memory: 9G
                reservations:
                    cpus: '3.00'
                    memory: 6G
        ports:
          - "9443:5100"
        environment:
          - ASPNETCORE_ENVIRONMENT=DockerProduction
          - ASPNETCORE_Kestrel__Certificates__Default__Password=fevrips2024*
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificates/fevripsapilocal.pfx
        volumes:
          - C:\Certificates:/certificates
        networks:
          - fevrips-net
        depends_on:   
          - fevrips-db

 # Nota: validar documentación referente, para los recuros del límite y reserva del contenedor 

