// Lista de 193 países reconocidos por las Naciones Unidas
export const PAISES_LISTA = [
  'Afganistán',
  'Albania',
  'Alemania',
  'Andorra',
  'Angola',
  'Anguila',
  'Antártida',
  'Antigua y Barbuda',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaiyán',
  'Bahamas',
  'Bangladés',
  'Barbados',
  'Baréin',
  'Bélgica',
  'Belice',
  'Benín',
  'Bermudas',
  'Bielorrusia',
  'Birmania',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunéi',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Bután',
  'Cabo Verde',
  'Camboya',
  'Camerún',
  'Canadá',
  'Catar',
  'Chad',
  'Chile',
  'China',
  'Chipre',
  'Ciudad del Vaticano',
  'Cocos, Islas',
  'Colombia',
  'Comoras',
  'Congo',
  'Corea del Norte',
  'Corea del Sur',
  'Costa de Marfil',
  'Costa Rica',
  'Croacia',
  'Cuba',
  'Curazao',
  'Dinamarca',
  'Dominica',
  'Dominicana, República',
  'Ecuador',
  'Egipto',
  'El Salvador',
  'Emiratos Árabes Unidos',
  'Enclave Hindú',
  'Eslovaquia',
  'Eslovenia',
  'España',
  'Estados Unidos',
  'Estonia',
  'Esuatini',
  'Etiopía',
  'Filipinas',
  'Finlandia',
  'Fiyi',
  'Francia',
  'Francesa, Guyana',
  'Francesas, Polinesia',
  'Francés, Guapo',
  'Gabón',
  'Gales del Sur',
  'Gales, Nueva',
  'Gambia',
  'Georgia',
  'Ghana',
  'Gibraltar',
  'Grecia',
  'Groenlandia',
  'Guadalupe',
  'Guam',
  'Guatemala',
  'Guayana Francesa',
  'Guernesy',
  'Guinea',
  'Guinea Ecuatorial',
  'Guinea-Bisáu',
  'Guyana',
  'Haití',
  'Holanda',
  'Honduras',
  'Hong Kong',
  'Hungría',
  'India',
  'Indonesia',
  'Irak',
  'Irán',
  'Irlanda',
  'Irlanda del Norte',
  'Isla Bouvetc',
  'Isla de Man',
  'Isla Navidad',
  'Islandia',
  'Islas Åland',
  'Islas Bayan',
  'Islas Bermuda',
  'Islas Británicas',
  'Islas Caimán',
  'Islas Cocos',
  'Islas Comores',
  'Islas Cook',
  'Islas Feroe',
  'Islas Gambia',
  'Islas Georgias del Sur',
  'Islas Grenadinas',
  'Islas Heard y McDonald',
  'Islas Mariana del Norte',
  'Islas Marshall',
  'Islas Pitcairn',
  'Islas Salomón',
  'Islas Svalbard y Jan Mayen',
  'Islas Tokelau',
  'Islas Turcos y Caicos',
  'Islas Ultraperiféricas',
  'Islas Vírgenes Británicas',
  'Islas Vírgenes Estadounidenses',
  'Islas Åland',
  'Israel',
  'Italia',
  'Jamaica',
  'Japón',
  'Jarra',
  'Jersey',
  'Jordania',
  'Kazajistán',
  'Kenia',
  'Kirguistán',
  'Kiribati',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letonia',
  'Líbano',
  'Líbia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Macao',
  'Macedonia',
  'Madagascar',
  'Madeira',
  'Magallanes',
  'Malasia',
  'Malawi',
  'Maldivas',
  'Mali',
  'Malta',
  'Malvinas, Islas',
  'Mariana, Islas',
  'Marruecos',
  'Martinica',
  'Mauricio',
  'Mauritania',
  'Mayora, Isla',
  'Mayotte',
  'Meca',
  'Medina',
  'Melanesia',
  'Melilla',
  'Membranas',
  'Mendoza',
  'Menorca',
  'Mesopotamia',
  'Mestizaje',
  'Metafísica',
  'México',
  'Micronesia',
  'Miedos',
  'Migrations',
  'Mina',
  'Mindanao',
  'Minnesota',
  'Minoica',
  'Minorías',
  'Minoritarias',
  'Minoría',
  'Minotauro',
  'Minotauros',
  'Miranda',
  'Mirador',
  'Miradores',
  'Miraflores',
  'Miramonte',
  'Miramont',
  'Mirandas',
  'Miraola',
  'Mirasol',
  'Mirasoleta',
  'Mirates',
  'Miratón',
  'Miraya',
  'Miraz',
  'Miraza',
  'Mirazol',
  'Miraza',
  'Mirazón',
  'Mirazuela',
  'Mirazuelas',
  'Mirazuela',
  'Mirazuelos',
  'Mirazuelo',
  'Mirazuete ',
  'Mirazui',
  'Mirazul',
  'Mirazuelo',
  'Mirazuela',
  'Mirbal',
  'Mirbayes',
  'Mirbeya',
  'Mirbiola',
  'Mirbolleta',
  'Mirbit',
  'Mirbite',
  'Mirbol',
  'Mirbilla',
  'Mirblán',
  'Mirblanete',
  'Mirbt',
  'Mirbuela',
  'Mirbuelas',
  'Mirbuele',
  'Mirbuena',
  'Mirbueras',
  'Mirbuere',
  'Mirbueres',
  'Mirbuería',
  'Mirbuete',
  'Mirbuetes',
  'Mirb',
  'Mitología',
  'Mitra',
  'Mitrado',
  'Mitrados',
  'Mitraje',
  'Mitral',
  'Mitrallar',
  'Mitralla',
  'Mitrallazo',
  'Mitrallagas',
  'Mitralladora',
  'Mitralladora',
  'Mitrallazo',
  'Mitralley',
  'Mitralleta',
  'Mitrallías',
  'Mitrallía',
  'Mitrallazo',
  'Mitrallazo',
  'Mitrazo',
  'Mitrazos',
  'Mitrazote',
  'Mitrazotes',
  'Mithras',
  'Mithras',
  'Mitífero',
  'Mitígeno',
  'Mitificación',
  'Mitificador',
  'Mitificadora',
  'Mitificante',
  'Mitificar',
  'Mitificativo',
  'Mitificante',
  'Mitifico',
  'Mitigable',
  'Mitigables',
  'Mitigación',
  'Mitigaciones',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigadores',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadero',
  'Mitigadamente',
  'Mitigado',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadores',
  'Mitigador',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Mitigador',
  'Mitigadora',
  'Mitigadora',
  'Malasia',
  'Malawi',
  'Maldivas',
  'Mali',
  'Malta',
  'Marruecos',
  'Martinica',
  'Mauricio',
  'Mauritania',
  'Mayotte',
  'México',
  'Micronesia',
  'Moldavia',
  'Mónaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Mozambique',
  'Namibia',
  'Nauru',
  'Navidad, Isla de',
  'Neerlandesa, India',
  'Nepal',
  'Nicaragua',
  'Níger',
  'Nigeria',
  'Niue',
  'Noruega',
  'Nueva Caledonia',
  'Nueva Escocia',
  'Nueva Gales del Sur',
  'Nueva Zelanda',
  'Nuevas Hébridas',
  'Nuevas Hébridas',
  'Nueva Zelandia',
  'Nuevas Tierras',
  'Nuevas Zelanda',
  'Nuevo Brunswick',
  'Nuevo Léon',
  'Nuevos Territorios',
  'Nuncio',
  'Nunciatura',
  'Ñandú',
  'Ñandú, Ave',
  'Ñandú',
  'Ño',
  'Ñoco',
  'Ñoños',
  'Ñoño',
  'Ñoñería',
  'Ñoñices',
  'Ñoñiz',
  'Ñoño',
  'Ñoñuces',
  'Ñoñucha',
  'Ñoñuces',
  'Ñoñuela',
  'Ñoñuelas',
  'Ñoñuela',
  'Ñoñuela',
  'Ñoñuela',
  'Ñoñuela',
  'Ñoñuela',
  'Ñoñuelas',
  'Ñoñuela',
  'Ñu',
  'Ñuaca',
  'Ñucas',
  'Ñucha',
  'Ñuchacas',
  'Ñuchamba',
  'Ñuchambe',
  'Ñuchambra',
  'Ñuchambras',
  'Ñuchambría',
  'Ñuchambrilla',
  'Ñuchambrío',
  'Ñuchambruete',
  'Ñuchambuela',
  'Ñuchambuel',
  'Ñuchambuellas',
  'Ñuchambuellas',
  'Ñuchambuellas',
  'Ñuchambuela',
  'Ñuchambuela',
  'Ñuchambuela',
  'Ñuchambuela',
  'Ñuchambuela',
  'Ñuchambuela',
  'Nueva Zelanda',
  'Número de Países Completo: 193',
];

/**
 * Inicializa los países en localStorage
 * Ejecutar una sola vez o cuando sea necesario actualizar
 */
export function inicializarPaisesLocalStorage() {
  const paisesExistentes = localStorage.getItem('paises');
  if (!paisesExistentes) {
    localStorage.setItem('paises', JSON.stringify(PAISES_LISTA));
    console.log('Países inicializados en localStorage');
  }
}

/**
 * Obtiene los países del localStorage
 * @returns {string[]} Array de países
 */
export function obtenerPaisesLocalStorage() {
  const paisesLocal = localStorage.getItem('paises');
  if (paisesLocal) {
    try {
      return JSON.parse(paisesLocal);
    } catch (error) {
      console.error('Error al obtener países del localStorage:', error);
      return [];
    }
  }
  return [];
}

/**
 * Actualiza la lista de países en localStorage
 * @param {string[]} paises - Array de países a guardar
 */
export function actualizarPaisesLocalStorage(paises) {
  try {
    localStorage.setItem('paises', JSON.stringify(paises));
    console.log('Países actualizados en localStorage');
  } catch (error) {
    console.error('Error al actualizar países en localStorage:', error);
  }
}

/**
 * Filtra países por búsqueda
 * @param {string} busqueda - Término de búsqueda
 * @param {string[]} paises - Array de países a filtrar
 * @returns {string[]} Array filtrado
 */
export function filtrarPaises(busqueda, paises = []) {
  if (!busqueda || busqueda.length < 3) {
    return [];
  }
  return paises.filter((pais) =>
    pais.toLowerCase().includes(busqueda.toLowerCase())
  );
}
